export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const GET_ALL_RESTAURANTS = "GET_ALL_RESTAURANTS";
export const DELETE_RESTAURANT = "DELETE_RESTAURANT";
export const GET_RESTAURANT = "GET_RESTAURANT";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";